# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Pier-Luc, votre spécialiste en planification, infrastructure et développement Web"
email: pierluc@pierluc.io
description: "Spécialisé dans le développement d'applications Web fiables, extensibles et modernes pour petites et moyennes entreprises."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pierluc.io" # the base hostname & protocol for your site
asseturl: "https://storage01.pierluc.io/pierluc-io"
twitter_username: Zertz
stackoverflow_userid: 1779688
github_username:  Zertz
facebook_app_id: 164646117285802

# Build settings
markdown: kramdown
highlighter: rouge
