# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Pier-Luc, votre spécialiste en planification, infrastructure et développement Web :: pierluc.io"
email: pierluc@pierluc.io
description: "Pier-Luc, votre spécialiste en planification, infrastructure et développement Web."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pierluc.io" # the base hostname & protocol for your site
twitter_username: Zertz
github_username:  Zertz

# Build settings
markdown: kramdown
highlighter: rouge
