# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Pier-Luc, votre spécialiste en développement, infrastructure et performance Web"
email: pierluc@pierluc.io
description: "Je suis un développeur spécialisé dans les technologies Web à la fine pointe. J'offre des services de consultation et de développement d'applications adaptatives et mobiles pour petites et moyennes entreprises."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pierluc.io" # the base hostname & protocol for your site
asseturl: "https://www.pierluc.io/images"
twitter_username: Zertz
stackoverflow_userid: 1779688
github_username:  Zertz
facebook_app_id: 164646117285802

# Build settings
markdown: kramdown
highlighter: rouge
exclude: ["Dockerfile", "nginx.conf", "README.md"]
